---
- name: create multiple nginx container for load balancing
  hosts: all
  tasks:
    - name: create 10 containers
      docker_container:
        name: "container{{item}}"
        image: nginx
      with_sequence: count=10

