--- 
  - name: configure tomcat
    hosts: all
    tasks: 
       - name: install tomcat9 and tomcat9-admin 
         apt: 
           name: "{{item.a}}"
           state: "{{item.b}}"
           update_cache: "{{item.c}}"
         with_items: 
           - {a: tomcat9,b: present,c: yes}
           - {a: tomcat9-admin,b: present,c: no}
       - name: copy tomcat-users.xml file
         copy: 
           src: tomcat-users.xml
           dest: /etc/tomcat9
       - name: change port of tomcat from 9090 to 8080 
         replace: 
           regexp: 8080
           replace: 9090
           path: /etc/tomcat9/server.xml
       - name: restart tomcat9
         service:
           name: tomcat9
           state: restarted 
       - name: pause for 1 min
         pause:
           minutes: 1
       - name: check tomcat on all managed nodes
         uri:
           url: "{{item}}"
           status_code: 200
         with_items:
           - http://172.31.81.198:9090
           - http://172.31.86.149:9090
... 
