---
  - name: install s/w applications
    hosts: all
    tasks: 
       - name: install/uninstall
         apt:
           name: "{{a}}"
           state: "{{b}}" 
           update_cache: "{{c}}"
...
